### ISSUE TITLE
General To-Do list and problems for me and others

### ISSUE THREAD

**Issue by Meronat** [LanternPowered/LanternServer#11]
- [ ] Cannot retrieve the item in player's hand, attempts to use some equipment system for it at the moment, but does not work

- [ ] No supplier for ItemStack.Builder

- [ ] BlockRays do not work properly if at all

- [ ] Noteblocks do not function

- [ ] Cannot spawn some types of rails

- [ ] Grabbing spawn eggs removes their type

- [ ] Cannot spawn jukebox(or I assume place disks in them)

- [ ] Attacking, taking damage, running, swimming, and jumping don't take your exhaustion away

- [ ] All durability items like swords, pickaxes, and armor spawn with "unbreakable" tag

- [ ] Can spawn bed but cannot place one

- [ ] **Multiplayer kind of works, but player location is not updated for others, so people don't move**

- [ ] It seems to be raining more than it should.

- [ ] Setting user on fire with Nucleus for x ticks leaves them on fire indefinitely 

- [ ] Nucleus spawn does not think set location is safe

- [ ] Keep getting warning about attempted offer of item durability to a fishing pole

- [ ] Nucleus cannot set vanish status nor can I

- [ ] Dropping item physics is strange. Doesn't project out and falls SUPER slowly, sometimes they will float a few blocks in the air

- [ ] Walking over magma blocks does not hurt you(need to make a new behavior)

- [ ] Breaking blocks does not drop them

- [ ] No message(neither chat or action bar) sent when trying to build over 265

- [ ] Unlocks all recipes when you join every time, but still red in recipe book

- [ ] You can spawn the default heads but you cannot place them

**Comment by Cybermaxke** [comment]
`No supplier for ItemStack.Builder` will be resolved in the recipes branch.

`Unlocks all recipes when you join every time, but still red in recipe book`, the red just means that you don't have enough resources to craft the recipe.

**Comment by Meronat** [comment]
**MC Commands To Implement**
---

- [ ] /advancement

- [ ] /blockdata

- [ ] /clear

- [ ] /clone - I never liked these commands. Maybe we should consider a more advanced world editing system?

- [ ] /debug

- [ ] /defaultgamemode ????

- [ ] /effect

- [ ] /enchant

- [ ] /entitydata

- [ ] /execute

- [ ] /fill - REFER TO /CLONE

- [ ] /function - Function complicated

- [ ] /give

- [ ] /locate - We need to make this better than Minecraft's

- [ ] /recipe 

- [ ] /reload - Can reload more than loot tables, advancements, and functions. Possibly lantern configs

- [ ] /replaceitem

- [ ] /save-all - Is this necessary?

- [ ] /save-on and /save-off - Kind of strange. Low priority

- [ ] /setblock REFER TO /CLONE

- [ ] /setmaxplayers - This is a PE only feature, maybe we should add it as a rule? Or is it somewhere already?

- [ ] /spawnpoint

- [ ] /spreadplayers - This command is cool

- [ ] /stats

- [ ] /summon 

- [ ] /tellraw - Not sure how useful this is

- [ ] /testfor These test for commands are strange

- [ ] /testforblock

- [ ] /testforblocks

- [ ] /trigger

- [ ] /wsserver - Okay this is PE only but could be interesting to implement

- [ ] /xp

**Other Commands To Implement**
---

- [ ]  /get-data

- [ ] /spawn

- [ ] /lantern version

- [ ] /lantern plugin list - Not sure how to set up this and the other plugin commands

- [ ] /lantern plugin info 

- [ ] /lantern plugin reload

- [ ] /lantern plugin reloadall

- [ ] /lantern timings

- [ ] /lantern info/chunk/etc

**Comment by Cybermaxke** [comment]
`It seems to be raining more than it should?`
There is currently a 33,3% chance that it rains, is clear or thunderstorms. I designed the weather system that you can register more weathers and when the weather changes it will always be a different one. I don't know how the vanilla system exactly works, but I think that they combine the thunder and rain weathers. Any suggestions what a realistic rate would be? I would say: `50% clear, 30% rain, 20% thunderstorm`?

**Comment by Cybermaxke** [comment]
@Meronat

**Comment by Meronat** [comment]
@Cybermaxke I think those rates are much more realistic for now, since I don't know much about the Minecraft weather system either.
